const { REACT_APP_NAME, REACT_APP_GITHUB_TOKEN, REACT_APP_GITHUB_API } = process.env;

export const APP_NAME = REACT_APP_NAME;
export const GITHUB_TOKEN = REACT_APP_GITHUB_TOKEN;
export const GITHUB_API = REACT_APP_GITHUB_API;
